---
- name: Create Ansible folder
  hosts: all
  become: true

  tasks:
    - name: Create ansible directory
      ansible.builtin.file:
      path: /home/ubuntu/ansible
      state: directory
      owner: sysadmin
      group: users
      mode: 0775
      recurse: yes 
